#include "CTextStack/constructors.c"
#include "CTextStack/admnistrative_methods.c"
#include "CTextStack/algo_methods.c"
#include "CTextStack/render_methods.c"
#include "CTexStackModule/CTextStackModule.c"