//
// Created by jurandi on 18-04-2023.
//
#define HTML "html"
#define BODY "body"
#define DIV "div"
#define H1 "h1"
#define H2 "h2"
#define H3 "h3"
#define H4 "h4"
#define H5 "h5"
#define H6 "h6"
#define P "p"
#define SPAN "span"
#define A "a"
#define IMG "img"
#define INPUT "input"
#define BUTTON "button"
#define TABLE "table"
#define TR "tr"
#define TD "td"
#define TH "th"
#define THEAD "thead"
#define TBODY "tbody"
#define TFOOT "tfoot"
#define UL "ul"
#define LI "li"
#define OL "ol"
#define FORM "form"
#define LABEL "label"
#define SELECT "select"
#define OPTION "option"
#define TEXTAREA "textarea"
#define SCRIPT "script"
#define STYLE "style"
#define META "meta"
#define LINK "link"
#define HEAD "head"
#define BASE "base"
#define BR "br"
#define HR "hr"
#define TITLE "title"
#define IFRAME "iframe"
#define NAV "nav"
#define HEADER "header"
#define FOOTER "footer"
#define SECTION "section"
#define ARTICLE "article"
#define ASIDE "aside"
#define DETAILS "details"
#define SUMMARY "summary"
#define DIALOG "dialog"
#define MENU "menu"
#define MENUITEM "menuitem"
#define MAIN "main"
#define CANVAS "canvas"
#define AUDIO "audio"
#define VIDEO "video"
#define SOURCE "source"
#define TRACK "track"
#define EMBED "embed"
#define PARAM "param"
    



